language: node_js
node_js:
  - 12

cache:
  directories:
    - node_modules

before_install:
  - npm i

script:
  - npm run prod

artifacts:
  files:
    - "**/*"
    dicard-paths: no
    base-directory: dist

deploy:
  
  - provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: vuetravistest
    application: VueTravisTest
    deployment_group: VueTravisTest-Dev
# deploy:
#   provider: s3
#   access_key_id: $AWS_KEY
#   secret_access_key: $AWS_SECRET
#   bucket: 'myvotebucket'
#   skip_cleanup: true
#   acl: public_read
#   local_dir: public
